import type { PlayerPosition } from '@/types'

export interface FormationTemplate {
  id: string
  name: string
  side: 'offense' | 'defense'
  players: PlayerPosition[]
}

export const OFFENSE_FORMATIONS: FormationTemplate[] = [
  {
    id: 'i-formation',
    name: 'I-Formation',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 32, label: 'Q' },
      { id: 'FB', position: 'FB', x: 50, y: 26, label: 'F' },
      { id: 'RB', position: 'RB', x: 50, y: 20, label: 'R' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'TE', position: 'TE', x: 67, y: 37, label: 'Y' },
      { id: 'X', position: 'WR', x: 15, y: 37, label: 'X' },
      { id: 'Z', position: 'WR', x: 88, y: 37, label: 'Z' },
    ],
  },
  {
    id: 'shotgun-2x2',
    name: 'Shotgun 2x2',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 30, label: 'Q' },
      { id: 'RB', position: 'RB', x: 44, y: 28, label: 'R' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'X', position: 'WR', x: 15, y: 37, label: 'X' },
      { id: 'H', position: 'WR', x: 25, y: 35, label: 'H' },
      { id: 'Y', position: 'WR', x: 75, y: 35, label: 'Y' },
      { id: 'Z', position: 'WR', x: 88, y: 37, label: 'Z' },
    ],
  },
  {
    id: 'spread',
    name: 'Spread (Empty)',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 30, label: 'Q' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'X', position: 'WR', x: 10, y: 37, label: 'X' },
      { id: 'H', position: 'WR', x: 25, y: 35, label: 'H' },
      { id: 'Y', position: 'WR', x: 75, y: 35, label: 'Y' },
      { id: 'Z', position: 'WR', x: 90, y: 37, label: 'Z' },
      { id: 'RB', position: 'RB', x: 82, y: 35, label: 'R' },
    ],
  },
  {
    id: 'singleback',
    name: 'Singleback (Ace)',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 32, label: 'Q' },
      { id: 'RB', position: 'RB', x: 50, y: 24, label: 'R' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'TE', position: 'TE', x: 67, y: 37, label: 'Y' },
      { id: 'X', position: 'WR', x: 15, y: 37, label: 'X' },
      { id: 'H', position: 'WR', x: 25, y: 35, label: 'H' },
      { id: 'Z', position: 'WR', x: 88, y: 37, label: 'Z' },
    ],
  },
  {
    id: 'pistol',
    name: 'Pistol',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 32, label: 'Q' },
      { id: 'RB', position: 'RB', x: 50, y: 24, label: 'R' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'X', position: 'WR', x: 15, y: 37, label: 'X' },
      { id: 'H', position: 'WR', x: 25, y: 35, label: 'H' },
      { id: 'Y', position: 'WR', x: 75, y: 35, label: 'Y' },
      { id: 'Z', position: 'WR', x: 88, y: 37, label: 'Z' },
    ],
  },
  {
    id: 'goal-line-o',
    name: 'Goal Line',
    side: 'offense',
    players: [
      { id: 'QB', position: 'QB', x: 50, y: 32, label: 'Q' },
      { id: 'FB', position: 'FB', x: 50, y: 26, label: 'F' },
      { id: 'RB', position: 'RB', x: 50, y: 20, label: 'R' },
      { id: 'LT', position: 'OL', x: 38, y: 37, label: 'T' },
      { id: 'LG', position: 'OL', x: 44, y: 37, label: 'G' },
      { id: 'C', position: 'OL', x: 50, y: 37, label: 'C' },
      { id: 'RG', position: 'OL', x: 56, y: 37, label: 'G' },
      { id: 'RT', position: 'OL', x: 62, y: 37, label: 'T' },
      { id: 'TE1', position: 'TE', x: 33, y: 37, label: 'Y' },
      { id: 'TE2', position: 'TE', x: 67, y: 37, label: 'U' },
      { id: 'WR', position: 'WR', x: 88, y: 37, label: 'Z' },
    ],
  },
]

export const DEFENSE_FORMATIONS: FormationTemplate[] = [
  {
    id: '4-3',
    name: '4-3',
    side: 'defense',
    players: [
      { id: 'DE1', position: 'DL', x: 36, y: 40, label: 'E' },
      { id: 'DT1', position: 'DL', x: 46, y: 40, label: 'T' },
      { id: 'DT2', position: 'DL', x: 54, y: 40, label: 'T' },
      { id: 'DE2', position: 'DL', x: 64, y: 40, label: 'E' },
      { id: 'WLB', position: 'LB', x: 40, y: 46, label: 'W' },
      { id: 'MLB', position: 'LB', x: 50, y: 46, label: 'M' },
      { id: 'SLB', position: 'LB', x: 60, y: 46, label: 'S' },
      { id: 'CB1', position: 'DB', x: 15, y: 44, label: 'C' },
      { id: 'CB2', position: 'DB', x: 88, y: 44, label: 'C' },
      { id: 'FS', position: 'DB', x: 50, y: 56, label: 'F' },
      { id: 'SS', position: 'DB', x: 65, y: 52, label: 'S' },
    ],
  },
  {
    id: '3-4',
    name: '3-4',
    side: 'defense',
    players: [
      { id: 'DE1', position: 'DL', x: 38, y: 40, label: 'E' },
      { id: 'NT', position: 'DL', x: 50, y: 40, label: 'N' },
      { id: 'DE2', position: 'DL', x: 62, y: 40, label: 'E' },
      { id: 'LOLB', position: 'LB', x: 32, y: 44, label: 'J' },
      { id: 'ILB1', position: 'LB', x: 44, y: 46, label: 'M' },
      { id: 'ILB2', position: 'LB', x: 56, y: 46, label: 'W' },
      { id: 'ROLB', position: 'LB', x: 68, y: 44, label: 'S' },
      { id: 'CB1', position: 'DB', x: 15, y: 44, label: 'C' },
      { id: 'CB2', position: 'DB', x: 88, y: 44, label: 'C' },
      { id: 'FS', position: 'DB', x: 50, y: 56, label: 'F' },
      { id: 'SS', position: 'DB', x: 65, y: 52, label: 'S' },
    ],
  },
  {
    id: 'nickel',
    name: 'Nickel (4-2-5)',
    side: 'defense',
    players: [
      { id: 'DE1', position: 'DL', x: 36, y: 40, label: 'E' },
      { id: 'DT1', position: 'DL', x: 46, y: 40, label: 'T' },
      { id: 'DT2', position: 'DL', x: 54, y: 40, label: 'T' },
      { id: 'DE2', position: 'DL', x: 64, y: 40, label: 'E' },
      { id: 'MLB', position: 'LB', x: 44, y: 46, label: 'M' },
      { id: 'WLB', position: 'LB', x: 56, y: 46, label: 'W' },
      { id: 'CB1', position: 'DB', x: 15, y: 44, label: 'C' },
      { id: 'CB2', position: 'DB', x: 88, y: 44, label: 'C' },
      { id: 'NB', position: 'DB', x: 75, y: 42, label: 'N' },
      { id: 'FS', position: 'DB', x: 50, y: 56, label: 'F' },
      { id: 'SS', position: 'DB', x: 65, y: 52, label: 'S' },
    ],
  },
  {
    id: 'dime',
    name: 'Dime (4-1-6)',
    side: 'defense',
    players: [
      { id: 'DE1', position: 'DL', x: 36, y: 40, label: 'E' },
      { id: 'DT1', position: 'DL', x: 46, y: 40, label: 'T' },
      { id: 'DT2', position: 'DL', x: 54, y: 40, label: 'T' },
      { id: 'DE2', position: 'DL', x: 64, y: 40, label: 'E' },
      { id: 'MLB', position: 'LB', x: 50, y: 46, label: 'M' },
      { id: 'CB1', position: 'DB', x: 15, y: 44, label: 'C' },
      { id: 'CB2', position: 'DB', x: 88, y: 44, label: 'C' },
      { id: 'NB1', position: 'DB', x: 25, y: 42, label: 'N' },
      { id: 'NB2', position: 'DB', x: 75, y: 42, label: 'N' },
      { id: 'FS', position: 'DB', x: 44, y: 56, label: 'F' },
      { id: 'SS', position: 'DB', x: 56, y: 52, label: 'S' },
    ],
  },
  {
    id: 'goal-line-d',
    name: 'Goal Line (6-2)',
    side: 'defense',
    players: [
      { id: 'DE1', position: 'DL', x: 30, y: 40, label: 'E' },
      { id: 'DT1', position: 'DL', x: 40, y: 40, label: 'T' },
      { id: 'NT', position: 'DL', x: 48, y: 40, label: 'N' },
      { id: 'DT2', position: 'DL', x: 56, y: 40, label: 'T' },
      { id: 'DE2', position: 'DL', x: 64, y: 40, label: 'E' },
      { id: 'DE3', position: 'DL', x: 72, y: 40, label: 'E' },
      { id: 'ILB1', position: 'LB', x: 44, y: 46, label: 'M' },
      { id: 'ILB2', position: 'LB', x: 56, y: 46, label: 'W' },
      { id: 'CB1', position: 'DB', x: 15, y: 44, label: 'C' },
      { id: 'CB2', position: 'DB', x: 88, y: 44, label: 'C' },
      { id: 'SS', position: 'DB', x: 50, y: 52, label: 'S' },
    ],
  },
]

export function getFormationById(id: string): FormationTemplate | undefined {
  return [...OFFENSE_FORMATIONS, ...DEFENSE_FORMATIONS].find((f) => f.id === id)
}
